### ISSUE TITLE
Add placeholder drawer that opens and closes on app language button press in settings pane

### ISSUE THREAD

**Issue by Harjot1Singh** [shabados/mobile#211]

**Comment by bhajneet** [comment]
We have not discussed how this will look in landscape. But I imagine the default is to fullscreen and not allow drag down, but "done" button press works or maybe slide from side. Not sure, curious to test.

**Comment by Harjot1Singh** [comment]
I did something explicit for this - it shows the modal still but with higher height and a fixed width in the middle.

**Comment by bhajneet** [comment]
The landscape modal is exactly what I envisioned, great foresight there.

It might be better to set a higher height on portrait as well, or otherwise indicate a list with a scrollbar? Because it's not evident that a user can scroll up and see more options.

- "panjābī" is being cut off (perhaps wrong line-height on title items)
- "hindī" is being just barely clipped at the top (same as second)
- once scrolled up on portrait (or just default open on landscape) there is a white bar at the bottom or a lack of background? not sure how to explain, here is a screenshot
![IMG_B5042EA95FA6-1](https://user-images.githubusercontent.com/14130567/159164263-009685bb-57ce-4746-9e31-5ce43d7553a5.jpeg)

**Comment by bhajneet** [comment]
I'm also able to break the modal, not sure if that falls under this issue. Reproduction:

- Swipe down most of the way (but do not dismiss, keep finger on screen)
- Rapidly tap the background (outside dimmed area)
- You do not have to let go of first finger to reproduce

You will get the following:


Note:

- You cannot tap app language button in landscape (it shows presses, but not working)
- You cannot tap done to close (it shows presses in portrait, but not working)
- Gets hidden in landscape and removes dimming (but I don't think you can even swipe out of settings)

**Comment by bhajneet** [comment]
Lastly, I believe the border-radius is too high for iOS (see "Apple Pay" implementation when paying). But I definitely don't mind either way and this border-radius issue doesn't seem to be a part of the ACs.

**Comment by bhajneet** [comment]
Initial setting is not being properly set for "English (UK, Canada, India)" etc. The app fallsback to whatever is below that. In the example below, if I reorder Hindi above French, then the app will use Hindi. As it is currently shown below, first install of the app defaults to French.

![IMG_29D7A87E9163-1](https://user-images.githubusercontent.com/14130567/159171782-08fc103f-8e4b-48e8-9b0c-d15dfe03d4c8.jpeg)
