### ISSUE TITLE
Investigate Styling Solutions

### ISSUE THREAD

**Issue by Harjot1Singh** [ShabadOS/mobile#99]
Do we need Native Base? Some questions:

- Where does it help us?
- Where does it work against us?
- Is it the standard to use a styling framework like Native Base on React Native?
- How far-away are the components we may need from what Native Base provides?
- Any examples of the equivalent Native Base vs plain component?

**Comment by saihaj** [comment]
* Where does it help us?
Theming

* Where does it work against us?
Similar to how in desktop we end up having  overriding classes for material UI components here we end up adding more styles to these to customize them to fit our unique design needs. 

* Is it the standard to use a styling framework like Native Base on React Native?
Don't think so because there are other (well documented) alternatives example: [React Native Elements](https://react-native-elements.github.io/react-native-elements), [UI Kitten](https://akveo.github.io/react-native-ui-kitten/)

* How far-away are the components we may need from what Native Base provides?
For example in search screen mockup we have filter strip. We can create it easily with RN ListView. I can also use NB but issue is that it has some styles that we don't really need so I end up overriding those. 

* Any examples of the equivalent Native Base vs plain component?
List vs FlatList


I feel like all React Native component libs are similar to [Bootstrap](https://getbootstrap.com) that they give you too many pre-built things and make life easy (only to some extent) we can customize them as much we want but after some point it is just easier to write css myself or start with something like [Tailwind](https://tailwindcss.com) that gives bare minimum so I can do whatever I want but making it easier than css.

**Comment by Harjot1Singh** [comment]
> Any examples of the equivalent Native Base vs plain component?
Re this question, I meant a component that someone might have written that utilises these, not the actual components themselves

> Don't think so because there are other (well documented) alternatives example: React Native Elements, UI Kitten
Do people tend to use UI frameworks? Can you take a look at some popular React Native apps and see what people use?

> Theming
Why would Native Base help us with theming over plain RN?

**Comment by saihaj** [comment]
> > Don't think so because there are other (well documented) alternatives example: React Native Elements, UI Kitten
Do people tend to use UI frameworks? Can you take a look at some popular React Native apps and see what people use?

I found this and top [3-4 projects](https://github.com/ReactNativeNews/React-Native-Apps) design wise look good and they use `react-native` one of the project I used `styled-components` but that is not a component lib.

> > Theming
Why would Native Base help us with theming over plain RN?

We get a ThemeProvider but we can implement our own.

**Comment by bhajneet** [comment]
Did you just top projects by number of stars? As in Joplin, AR Cut & Paste, GitPoint, etc?

**Comment by saihaj** [comment]
Just in the order they are written I was just looking for react native version and activity

**Comment by Harjot1Singh** [comment]
https://styled-components.com/docs/advanced#theming

**Comment by Harjot1Singh** [comment]
After going through the list @saihaj posted in detail, and evaluating Native Base again, I'm happy to dump it and go with writing our own components or installing what we need.

https://akveo.github.io/react-native-ui-kitten/ UI Kitten is the only UI framework I'd consider close to what we want.
